name: Bug Report
description: Report a bug or issue to help us improve
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! This helps us maintain quality and fix issues quickly.

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: What is the bug? What went wrong?
      placeholder: Provide a clear and concise description of the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Enter '...'
        4. See error
      value: |
        1. 
        2. 
        3. 
        4.
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What should have happened instead?
      placeholder: Describe what you expected to happen...
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Low - Minor issue, workaround available
        - Medium - Affects functionality but not critical
        - High - Major functionality broken
        - Critical - System/app unusable
      default: 1
    validations:
      required: true

  - type: input
    id: environment-os
    attributes:
      label: Operating System
      description: What OS are you using?
      placeholder: "e.g., Windows 11, macOS 14, Ubuntu 22.04"
    validations:
      required: false

  - type: input
    id: environment-browser
    attributes:
      label: Browser (if applicable)
      description: What browser and version?
      placeholder: "e.g., Chrome 120, Firefox 121, Safari 17"
    validations:
      required: false

  - type: input
    id: environment-version
    attributes:
      label: Application/Version
      description: What version of the application?
      placeholder: "e.g., v1.2.3, commit abc123"
    validations:
      required: false

  - type: textarea
    id: logs-errors
    attributes:
      label: Error Messages/Logs
      description: Include any relevant error messages, stack traces, or logs
      placeholder: Paste any error messages or relevant log output here...
      render: text
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Screenshots, videos, or any other context that would help
      placeholder: Add any other context about the problem here...
    validations:
      required: false
